version: '3.8'

services:
  # Основное приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosatom-support-agent
    ports:
      - "8501:8501"
    volumes:
      # Монтируем данные для персистентности
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - support-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx для reverse proxy (опционально)
  # nginx:
  #   image: nginx:alpine
  #   container_name: rosatom-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - support-network
  #   restart: unless-stopped

networks:
  support-network:
    driver: bridge

volumes:
  data:
  models:
  logs:
